/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#adc7f7",
        "on-primary-container": "#86a0cd",
        "surface-container-low": "#f0f3ff",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#002111",
        "secondary-fixed-dim": "#6bdc96",
        "on-secondary-fixed-variant": "#00522c",
        "surface-container-high": "#dee8ff",
        "primary-container": "#1a365d",
        "primary": "#002045",
        "outline-variant": "#c4c6cf",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005231",
        "surface-container-highest": "#d9e3f9",
        "surface-container": "#e7eeff",
        "tertiary-container": "#003f25",
        "surface-dim": "#d0daf0",
        "secondary-fixed": "#88f9b0",
        "tertiary-fixed": "#9ff5c1",
        "primary-fixed": "#d6e3ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-primary": "#adc7f7",
        "on-primary-fixed-variant": "#2d476f",
        "surface-variant": "#d9e3f9",
        "on-tertiary-container": "#5caf81",
        "error-container": "#ffdad6",
        "secondary": "#006d3c",
        "outline": "#74777f",
        "on-primary-fixed": "#001b3c",
        "error": "#ba1a1a",
        "on-secondary-container": "#00723f",
        "secondary-container": "#85f6ad",
        "inverse-surface": "#273141",
        "inverse-on-surface": "#ebf1ff",
        "surface-tint": "#455f88",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#43474e",
        "tertiary": "#002715",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#83d8a6",
        "surface-bright": "#f9f9ff",
        "surface": "#f9f9ff",
        "on-surface": "#121c2c",
        "on-tertiary": "#ffffff",
        "on-background": "#121c2c",
        "on-secondary-fixed": "#00210f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "xs": "4px",
        "unit": "8px",
        "container-padding": "16px",
        "xl": "32px",
        "md": "16px",
        "lg": "24px",
        "gutter": "16px"
      },
      fontFamily: {
        "h3": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}