# Generated by Django 6.0.4 on 2026-05-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygrowa', '0002_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='screenshot',
        ),
        migrations.AlterField(
            model_name='survey',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='paygrowa.task'),
        ),
    ]
