# Generated by Django 6.0.4 on 2026-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygrowa', '0003_remove_taskassignment_screenshot_alter_survey_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
