# Generated by Django 6.0.4 on 2026-05-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygrowa', '0004_alter_survey_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.JSONField(),
        ),
    ]
