# Generated by Django 6.0.4 on 2026-05-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygrowa', '0005_alter_survey_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('started', 'Started'), ('submitted', 'Submitted'), ('opt_out', 'Opted Out')], default='assigned', max_length=20),
        ),
    ]
